# Pre-Prefresher Exercises {-}


Before our first meeting, please try solving these questions. They are a sample of the very beginning of each math section. We have provided links to the parts of the book you can read if the concepts are new to you. 

The goal of this "pre"-prefresher assignment is not to intimidate you but to set common expectations so you can make the most out of the actual Prefresher. Even if you do not understand some or all of these questions after skimming through the linked sections, your effort will pay off and you will be better prepared for the math prefresher. We are also open to adjusting these expectations based on feedback (this class is for _you_), so please do not hesitate to write to the instructors for feedback. 



## Linear Algebra {-}

### Vectors {-}

Define the vectors $u = \begin{pmatrix} 1 \\2 \\3 \end{pmatrix}$, $v = \begin{pmatrix} 4\\5\\6 \end{pmatrix}$, and the scalar $c = 2$. Calculate the following:

1. $u + v$
2. $cv$
3. $u \cdot v$

If you are having trouble with these problems, please review Section \@ref(vector-def) "Working with Vectors" in Chapter \@ref(linearalgebra). 


Are the following sets of vectors linearly independent?

1. $u = \begin{pmatrix} 1\\ 2\end{pmatrix}$, $v = \begin{pmatrix} 2\\4\end{pmatrix}$


2. $u = \begin{pmatrix} 1\\ 2\\ 5 \end{pmatrix}$, $v = \begin{pmatrix} 3\\ 7\\ 9 \end{pmatrix}$


3. $a = \begin{pmatrix} 2\\ -1\\ 1 \end{pmatrix}$, $b = \begin{pmatrix} 3\\ -4\\ -2 \end{pmatrix}$, $c = \begin{pmatrix} 5\\ -10\\ -8 \end{pmatrix}$ (this requires some guesswork)


If you are having trouble with these problems, please review Section \@ref(linearindependence). 


### Matrices {-}

\[{\bf A}=\begin{pmatrix}
			7 & 5 & 1 \\
			11 & 9 & 3 \\ 
			2 & 14 & 21 \\ 
			4 & 1 & 5
		\end{pmatrix}\]
		
		
What is the dimensionality of matrix ${\bf A}$?

What is the element $a_{23}$ of ${\bf A}$?

Given that 
		
\[{\bf B}=\begin{pmatrix}
			1 & 2 & 8 \\
			3 & 9 & 11 \\ 
			4 & 7 & 5 \\ 
			5 & 1 & 9
		\end{pmatrix}\]
		
What is ${\bf A}$ + ${\bf B}$?


Given that 
		
\[{\bf C}=\begin{pmatrix}
			1 & 2 & 8 \\
			3 & 9 & 11 \\ 
			4 & 7 & 5 \\ 
		\end{pmatrix}\]
		
What is ${\bf A}$ + ${\bf C}$?



Given that 

\[c = 2\]

What is $c$${\bf A}$?

If you are having trouble with these problems, please review Section \@ref(matrixbasics). 



## Operations {-}

### Summation {-}

Simplify the following

1. \(\sum\limits_{i = 1}^3 i\)

2. \(\sum\limits_{k = 1}^3(3k + 2)\)

3. \(\sum\limits_{i= 1}^4 (3k + i + 2)\)


### Products {-}

1. \(\prod\limits_{i= 1}^3 i\)

2. \(\prod\limits_{k=1}^3(3k + 2)\)


To review this material, please see Section \@ref(sum-notation).


### Logs and exponents {-}

Simplify the following

1.  \(4^2\)
2.  \(4^2 2^3\)
3.  \(\log_{10}100\)
4.  \(\log_{2}4\)
5.  \(\log e\), where $\log$ is the natural log (also written as $\ln$) -- a log with base $e$, and $e$ is Euler's constant
6.  \(e^a e^b e^c\), where $a, b, c$ are each constants
7.  \(\log 0\)
8.  \(e^0\)
9.  \(e^1\)
10. \(\log e^2\)

To review this material, please see Section \@ref(logexponents)



## Limits {-}

Find the limit of the following.

1. $\lim\limits_{x \to 2} (x - 1)$
2. $\lim\limits_{x \to 2} \frac{(x - 2) (x - 1)}{(x - 2)}$
3. $\lim\limits_{x \to 2}\frac{x^2 - 3x + 2}{x- 2}$

To review this material please see Section \@ref(limitsfun)


## Calculus {-}

For each of the following functions $f(x)$, find the derivative $f'(x)$ or $\frac{d}{dx}f(x)$

1. $f(x)=c$
2. $f(x)=x$
3. $f(x)=x^2$
4. $f(x)=x^3$
5. $f(x)=3x^2+2x^{1/3}$
6. $f(x)=(x^3)(2x^4)$

For a review, please see Section \@ref(derivintro) - \@ref(derivpoly)

## Optimization {-}

For each of the followng functions $f(x)$, does a maximum and minimum exist in the domain $x \in \mathbf{R}$? If so, for what are those values and for which values of $x$?

1. $f(x) = x$
2. $f(x) = x^2$
3. $f(x) = -(x  - 2)^2$

If you are stuck, please try sketching out a picture of each of the functions.
	

## Probability {-}

1. If there are 12 cards, numbered 1 to 12, and 4 cards are chosen, how many distinct possible choices are there? (unordered, without replacement)
2. Let $A = \{1,3,5,7,8\}$ and $B = \{2,4,7,8,12,13\}$. What is $A \cup B$? What is $A \cap B$? If $A$ is a subset of the Sample Space $S = \{1,2,3,4,5,6,7,8,9,10\}$, what is the complement $A^C$? 
3. If we roll two fair dice, what is the probability that their sum would be 11?
4. If we roll two fair dice, what is the probability that their sum would be 12?


For a review, please see Sections \@ref(setoper) - \@ref(probdef).

