# Pre-PreFresher Exercises




## Linear Algebra

### Vectors

Given that $u = (1,2,3)$, $v = (4,5,6)$, and $c = 2$, Calculate the following:

1. $u + v$
2. $cv$
3. $uv$

If you are having trouble with these problems, please review section 2.1 "Working with Vectors" in Chapter 2. 


Are the following sets of vectors linearly independent?


1. $u = \begin{pmatrix} 1\\ 2\\ 5 \end{pmatrix}$, $b = \begin{pmatrix} 3\\ 7\\ 9 \end{pmatrix}$


2. $a = \begin{pmatrix} 2\\ -1\\ 1 \end{pmatrix}$, $b = \begin{pmatrix} 3\\ -4\\ -2 \end{pmatrix}$, $c = \begin{pmatrix} 5\\ -10\\ -8 \end{pmatrix}$


If you are having trouble with these problems, please review section 2.2 "Linear Independence" in Chapter 2. 


### Matrices

\[{\bf A}=\begin{pmatrix}
			7 & 5 & 1 \\
			11 & 9 & 3 \\ 
			2 & 14 & 21 \\ 
			4 & 1 & 5
		\end{pmatrix}\]
		
		
What is the dimensionality of matrix ${\bf A}$?

What is the element $a_{23}$ of ${\bf A}$?

Given that 
		
\[{\bf B}=\begin{pmatrix}
			1 & 2 & 8 \\
			3 & 9 & 11 \\ 
			4 & 7 & 5 \\ 
			5 & 1 & 9
		\end{pmatrix}\]
		
What is ${\bf A}$ + ${\bf B}$?


Given that 
		
\[{\bf C}=\begin{pmatrix}
			1 & 2 & 8 \\
			3 & 9 & 11 \\ 
			4 & 7 & 5 \\ 
		\end{pmatrix}\]
		
What is ${\bf A}$ + ${\bf C}$?



Given that 

\[c = 2\]

What is $c$${\bf A}$

If you are having trouble with these problems, please review section 2.3 "Basics of Matrix Algebra" in Chapter 2. 



## Operations


Simplify the following

1. $\sum^3_{i = 1} i$
2. $\sum^5_{k = 1}(3k + 7)$
3. $\sum^3_{i= 1} 3k + i + 7$



Simplify the following

1. $4^2$
2. $4^2 2^3$
3. $\log_{10}100$
4. $\log_{2}4$
5. $\log e$, where $\log$ is the natural log (alsowritten as $\ln$) -- a log with base $e$, and $e$ is Euler's constant
6. $e^a e^b e^c$, where $a, b, c$ are each constants
7. $\log 0$
8. $e^0$
9. $e^1$
10. $\log e^2$



## Limits

Find the limit of the following.

1. $\lim_{x \to 2} (x - 1)$
2. $\lim_{x \to 2} \frac{(x - 2) (x - 1)}{(x - 2)}$
3. $\lim_{x \to 2}\frac{x^2 - 3x + 2}{x- 2}$



## Calculus

For each of the following functions $f(x)$, find the derivative $f'(x)$ or $\frac{d}{dx}f(x)$

1. $f(x)=c$
2. $f(x)=x$
3. $f(x)=x^2$
4. $f(x)=x^3$
5. $f(x)=3x^2+2x^{1/3}$
6. $f(x)=(x^3)(2x^4)$
	

## Probability	

1. If we roll two fair dice, what is the probability that their sum would be 11?
2. If we roll two fair dice, what is the probability that their sum would be 12?