project:
  type: book
  output-dir: _book


book:
  title: "Math Prefresher for Political Scientists"
  description: "Text for Harvard Department of Government Math Prefresher"
  site-url: https://iqss.github.io/prefresher/
  chapters:
    - index.qmd
    - 01_warmup.qmd
    - part: Math
      chapters: 
        - 02_functions.qmd
        - 03_limits.qmd
        - 04_calculus.qmd
        - 05_optimization.qmd
  

delete_merged_file: true
language:
  ui:
    chapter_name: "Chapter "
    
github-repo: "IQSS/prefresher"
geometry: "margin=1.5in"
biblio-style: apalike
link-citations: true
cover-image: "./images/logo.png"
