project:
  type: book
  output-dir: _book

book:
  title: "Math Prefresher for Political Scientists"
  site-url: https://iqss.github.io/prefresher/
  chapters:
    - index.qmd
    - 01_warmup.qmd
    - part: Math
      chapters: 
        - 02_functions.qmd
        - 03_limits.qmd
  

delete_merged_file: true
language:
  ui:
    chapter_name: "Chapter "
