--- 
title: "Math Prefresher for Political Scientists"
author: ""
date: "`r Sys.Date()`"
description: "Text for Harvard Department of Government Math Prefresher"
github-repo: "kuriwaki/prefresher"
site: "bookdown::bookdown_site"
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
---

# About this Booklet {-}

The Harvard Gov Prefresher is held each year in August. All relevant information is on our website: <https://projects.iq.harvard.edu/prefresher>. The 2018 Prefresher instructors are [Shiro Kuriwaki](https://www.shirokuriwaki.com) and Yon Soo Park, and the faculty sponsor is  [Gary King](https://gking.harvard.edu). 


This booklet is the "text" for the Prefresher, and it is the product of generations of Prefresher Instructors: Curt Signorino 1996-1997; Ken Scheve 1997-1998; Eric Dickson 1998-2000; Orit Kedar 1999; James Fowler 2000-2001; Kosuke Imai 2001-2002; Jacob Kline 2002; Dan Epstein 2003; Ben Ansell 2003-2004; Ryan Moore 2004-2005; Mike Kellermann 2005-2006; Ellie Powell 2006-2007; Jen Katkin 2007-2008; Patrick Lam 2008-2009; Viridiana Rios 2009-2010; Jennifer Pan 2010-2011; Konstantin Kashin 2011-2012; Soledad Prillaman 2013; Stephen Pettigrew 2013-2014; Anton Strezhnev 2014-2015; Mayya Komisarchik 2015-2016; Connor Jerzak 2016-2017; Shiro Kuriwaki 2017-2018; Yon Soo Park 2018-


We transitioned the booklet into a Rmarkdown (bookdown) document and into a public github [repo](https://github.com/kuriwaki/prefresher) in 2018. As we update this version, any bug reports or fixes would be greatly appreciated. 
